### ISSUE TITLE
Suggestion, transition screen

### ISSUE THREAD

**Issue by dosluke** [stargate-rewritten/Stargate-Mechanics#14]
When I TP through a gate, it takes a second to load chunks before it activates the portal. Ive usuallly already stepped into the gate before the portal activates and im waiting for it. It would be cool if it activated immediately, and then if the chunks arnt loaded, it gives some sort of animation screen, kind of like starbounds teleport, but faster, and different, maybe like a starfield or something. idk.

**Comment by Thorinwasher** [comment]
As this is a spigot plugin and not a mod, we are dealing with reduced customizability of the game. But after some discussion this is the types of behaviors we can provide during teleportation:

- Show a text in the middle of the screen to the player when they are teleporting
- Add particles at the location the player is teleporting from
- Have a boss bar that says they are teleporting
- It might be possible to trigger the world change loading screen to the player, but I don't know how.

What do you think, do you have any ideas on effects that can be sent to a normal client, by only modifying the server?

**Comment by dosluke** [comment]
some sort of particle effect would probably be best imo... maybe a non damaging explosion right before tp? those other options seem at best annoying and at worst, possibly buggy. I dont know minecraft or spigot/bukkit apis at all so i have no idea whats possible but it definitely makes sense that theres reduced customization. either way there should be a minimum amount of customization on the config for disabling the feature, if not more.

**Comment by Thorinwasher** [comment]
Sound effects in general would be nice to have (but should of course be toggleable) this is a bit of a different feature request though. I can say that we can have an audio option for each action you can do on a gate (of course limited by vanilla sound effects)

- Sign scroll
- Button press
- Gate open
- Gate teleport

I can say that all of the alternatives I provided should be an option (maybe not the world loading screen if not possible), but that all of this fits perfectly into the planned Stargate-Customisations addon.
