### ISSUE TITLE
The `C` flag

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Mechanics#3]
Not compatible with the `A` flag.

When activated, a `C` portal will remain open for the specified amount of time.
For instance, this `C` portal will effectively be an A portal for 3 days.

(it will also be free and backwards)
```
gate1
gate2
networkName
[C:3d]BF
```

**Comment by Thorinwasher** [comment]
One alternative for both the C and D flag is to have this in an gui. But maybe this is better?

**Comment by Pheotis** [comment]
> One alternative for both the C and D flag is to have this in an gui. But maybe this is better?

I would prefer to avoid GUIs where possible, but I am not necessarily against it in this case given that it is in a module.
A potential alternative would be some sort of physical timer sign incremented by right-clicking.
It might also be possible to use the TIR variant as the main way to add time.
