### ISSUE TITLE
The `D` Flag.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Mechanics#4]
When created, a `D` portal will last for a specified amount of time.
After that time has lapsed, the portal will destroy itself.

For instance, this `D` portal will effectively be an A portal for 3 months.
(it will also be always-on)
```
gate1
gate2
networkName
[C:3m]A
```

**Comment by Thorinwasher** [comment]
So inside the [] did you mean `[D:3m]`

**Comment by Pheotis** [comment]
> So inside the [] did you mean `[D:3m]`

Whoops, this must have been copied and pasted.
Yes; although, I think `D[0d0h0m0s]` would make the most sense.
