### ISSUE TITLE
The `W` flag

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Mechanics#7]
The `W` flag will randomly teleport users into the world, within a radius specified in the config.

It will be able to operate with three modes:

#### Mode One
The user will just be teleported into the world.
No portal will generate at the destination.

#### Option Two
The user will be teleported into the world.
A portal will be generated at their destination.

This portal will be on a specific network.
Entering said portal will return the user to spawn.
OR (depending on config) randomly teleport the user to another portal generated through this method.

#### Option Three
The user will be randomly teleported to an existing ruined portal.
All ruined portals will be fixed and transformed into `nether.gate` stargates (or similar).

Entering said portal will return the user to spawn.
OR (depending on config) randomly teleport the user to another ruined portal generated through this method.

**Comment by Thorinwasher** [comment]
For these options, do you mean we should have that in the config as well?

**Comment by Pheotis** [comment]
> For these options, do you mean we should have that in the config as well?

Definitely; there will almost certainly need to yml file specifically for SG-Mechanics as a whole.
This option would just be a behaviour node within that config file.
